[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"

[invariant]
runs = 500
depth = 15
show_metrics = true
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
